#!/usr/bin/python

"""
Send an UDP message, wait for reply, print and exit.
"""

import socket
import sys

import set_paxos_path # MUST BE BEFORE PAXOS IMPORTS
from paxos.udp import UDP

def getlines(file):
  return "".join(file.readlines())

def listen(host, port, reply, timeout=5):
  u = UDP(host, port, timeout=timeout)
  print("Listening on UDP %s:%d" % (u.ip, u.port))

  while True:
    try:
      resp, (rip, rport) = u.recvfrom()
      print("%s:%d says: %s" % (rip, rport, resp.rstrip()))
      sys.stdout.flush()
      if reply:
        u.sendto((rip, rport), resp.upper())
    except KeyboardInterrupt:
      return 0
    except socket.timeout:
      pass

def usage():
  print("Usage: listen-udp [-r] [-wN] IP PORT")
  print("Listens for UDP messages on IP:PORT.")
  print("If -r is set, echoes uppercase input.")
  print("If -wN is set, use N for timeout (no spaces, please).")
  print("")
  print("Example:\n  listen-udp -r -w10 0.0.0.0 1234\n")
  sys.exit(1)

if __name__ == "__main__":
  args = sys.argv[1:]

  if len(args) < 2:
    usage()

  host = None
  port = None
  reply = False
  timeout = 5
  for arg in args:
    if arg == "-r":
      reply = True
    elif arg.startswith("-w"):
      timeout = int(arg[2:])
    elif host is None:
      host = arg
    elif port is None:
      port = int(arg)

  if host is None or port is None:
    usage()

  sys.exit(listen(host, port, reply, timeout))
