#!/usr/bin/python

"""
Send an UDP message, wait for reply, print and exit.
"""

import socket
import sys
import time

from paxos.udp import UDP

def getlines(file):
  if file == sys.stdin:
    print("Reading data from stdin")
  return "".join(file.readlines())

def send(host, port, reply, its, data, timeout=5):
  u = UDP(timeout=timeout)
  print("Sending %d bytes to %s:%d from %s:%d" %
        (len(data), host, port, u.ip, u.port))

  for it in xrange(its):
    start = time.time()
    u.sendto((host, port), data)
    if reply:
      try:
        resp, (rip, rport) = u.recvfrom()
        stop = time.time()
        print("RTT %.2f ms, %s:%d says: %s" % (
          (stop-start)*1000.0, rip, rport, resp.rstrip()))
        sys.stdout.flush()
      except KeyboardInterrupt:
        print("")
      except socket.timeout:
        print("Reply timed out")
        pass
  return 0

def usage():
  print("Usage: send-udp [-r] [-wN] IP PORT")
  print("Sends UDP message from stdin to IP:PORT.")
  print("")
  print("If -r flag is set, wait for response and print.")
  print("If -wN is set, wait N seconds (no spaces, please).")
  print("If -iN is set, run N times, for measuring RTT.")
  print("")
  print("Example:\n  echo howdy | send-udp -r -w10 127.0.0.1 1234\n")
  sys.exit(1)

if __name__ == "__main__":
  args = sys.argv[1:]

  if len(args) < 2:
    usage()

  host = None
  port = None
  reply = False
  timeout = 5
  its = 1
  for arg in args:
    if arg == "-r":
      reply = True
    elif arg.startswith("-w"):
      timeout = int(arg[2:])
    elif arg.startswith("-i"):
      its = int(arg[2:])
    elif host is None:
      host = arg
    elif port is None:
      port = int(arg)

  if host is None or port is None:
    usage()

  sys.exit(send(host, port, reply, its, getlines(sys.stdin), timeout))
